name: firedpy2  # Replace with your desired environment name
channels:
  - default
  - conda-forge  # Use the conda-forge channel for some packages
dependencies:
  - beautifulsoup4>=4.12.2
  - earthaccess
  - gdal>=3.9.2
  - geopandas>=1.0.1
  - libgdal-hdf4>=3.9.2
  - matplotlib>=3.9.2
  - mock>=5.1.0
  - netCDF4>=1.7.1
  - numpy>=2.1.2
  - pandas==2.2.3
  - paramiko>=3.5.0
  - rasterio>=1.4.1
  - requests>=2.32.3
  - scipy>=1.14.1
  - shapely>=2.0.6
  - tqdm>=4.66.5
  - xarray>=2023.8.0
