
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7df43d1375fee9174eb9314567c2464ed2d7e7a1",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
