
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-14T12:51:46-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "62943e2b90e46ee9b09b1e4811155c3d36f7ca8f",
 "version": "0.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
